name: 'DEV cluster creation workflow'
on:
  push:
    branches:
      - master
    paths:
      - 'clusters/eks/dev/**/input.yaml'
      - '!clusters/eks/**/foundation'
      - '!clusters/eks/**/terraform'

jobs:
  qamatrix:
    runs-on: cicd-dev
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

    - name: 'checkout code'
      uses: 'actions/checkout@v2'
      with:
        ref: master
        fetch-depth: 0
        token: ${{ secrets.BOT_GITHUB_PAT }}
    
    - id: set-matrix
      run: |
        BASE_JSON="{\"include\":["
        for i in `git diff-tree --no-commit-id --name-only -r ${{ github.sha }} --diff-filter=A| grep input.yaml | grep "clusters/eks/dev"`;do
          if [ `echo $i | grep input.yaml` ]
          then
            cluster_path=$(dirname $i)
            cluster_name=$(basename $(dirname $i))
            cluster_region=$(dirname $i | awk -F '/' '{print $4}')
            # Add build to the matrix only if it is not already included
            JSONline="{\"clusterName\":\"$cluster_name\", \"clusterPath\":\"$cluster_path\", \"clusterRegion\":\"$cluster_region\"},"
            if [[ "$BASE_JSON" != *"$JSONline"* ]]; then
              BASE_JSON="$BASE_JSON$JSONline"
            fi
          fi
        done
        # Remove last "," and add closing brackets
        if [[ $BASE_JSON == *, ]]; then
          BASE_JSON="${BASE_JSON%?}"
        fi
        BASE_JSON="$BASE_JSON]}"
        echo "$BASE_JSON"
        # Set output
        echo "::set-output name=matrix::$( echo "$BASE_JSON" )"
